version: "3.9"

services:
  web:
    image: vhistory:v1
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=Dedust!23
      - POSTGRES_DB=video_watch_history
