version: "3.9"

services:
  web:
    image: vhistory:v1
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=Dedust!23
      - POSTGRES_DB=video_watch_history

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
